from database import db

class Estoque(db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    Local = db.Column(db.String(255))
    F_IDLOCAL = db.Column(db.String(255))
    Tipo_do_Local = db.Column(db.String(255))
    Estado = db.Column(db.String(255))
    Buffer = db.Column(db.Boolean)
    Local_Ativo = db.Column(db.Boolean)
    Setor = db.Column(db.String(255))
    Regiao = db.Column(db.String(255))
    Estoque = db.Column(db.Integer)
    Pendencia = db.Column(db.Integer)
    Adicionar = db.Column(db.Integer)
    Disponivel = db.Column(db.Integer)
    Barra = db.Column(db.String(255))
    Descricao_Reduzida = db.Column(db.String(255))
    idProduto = db.Column(db.String(255))
    Codigo_do_Produto = db.Column(db.String(255))
    Codigo_Produto_Depositante = db.Column(db.String(255))
    Produto = db.Column(db.String(255))
    Depositante = db.Column(db.String(255))
    Tipo = db.Column(db.String(255))
    H_IDARMAZEM = db.Column(db.String(255))
    H_IDDEPOSITANTE = db.Column(db.String(255))
    H_ORDEM = db.Column(db.String(255))
    H_RN = db.Column(db.String(255))
    data_atualizacao = db.Column(db.DateTime)