"""empty message

Revision ID: 487fe4599c43
Revises: a41772aee6bd
Create Date: 2025-08-12 14:57:31.287742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '487fe4599c43'
down_revision = 'a41772aee6bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cargo', sa.String(length=32), nullable=False),
    sa.Column('rota', sa.String(length=128), nullable=False),
    sa.Column('pode_acessar', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissao')
    # ### end Alembic commands ###
