"""empty message

Revision ID: 59f0549b3aab
Revises: 
Create Date: 2025-08-12 09:56:30.855754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59f0549b3aab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barra_endereco', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])

    with op.batch_alter_table('user_credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_empresa', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'empresa', ['id_empresa'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_credential', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_empresa')

    with op.batch_alter_table('barra_endereco', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_empresa')

    # ### end Alembic commands ###
