"""empty message

Revision ID: a41772aee6bd
Revises: 46a201549a80
Create Date: 2025-08-12 14:44:41.875288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a41772aee6bd'
down_revision = '46a201549a80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruas_selecionadas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ruas_selecionadas_usuario_id_fkey'), type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ruas_selecionadas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('ruas_selecionadas_usuario_id_fkey'), 'usuario', ['usuario_id'], ['id'])

    # ### end Alembic commands ###
